os: osx
osx_image: xcode8
language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

sudo: true

notifications:
  email: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g cordova
  
before_script:
  - cordova platform add ios@4.3.0
  - cordova platform add android@6.0.0

script:
  - npm test