os: osx
osx_image: xcode8
dist: osx

language:
- objective-c
- android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23

sudo: false

notifications:
  email: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g cordova
  
before_script:
  - cordova platform add ios@4.3.0
  - cordova platform add android@6.0.0

script:
  - npm test