language: objective-c
os: osx
osx_image: xcode8

sudo: false

notifications:
  email: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - brew update
  - npm install cordova
  
before_script:
  - cordova platform add ios

script:
  - npm test