matrix:
  include:
    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-27
          - build-tools-27.0.3
      before_script:
        - npm install -g cordova
        - cordova platform add android@7
      script:
        - npm test

    - language: objective-c
      os: osx
      osx_image: xcode9.2
      before_script:
        - npm install -g cordova
        - cordova platform add ios@4
      script:
        - npm test
notifications:
  email: false