language: node_js
node_js:
  - 6

sudo: false

notifications:
  email: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  
before_script:
  - cordova plugin add cordova-custom-config@latest
